global using FluentValidation;
global using FluentValidation.Results;
global using FluentValidation.TestHelper;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;
global using MovieManagement.Functions.Dtos;
global using MovieManagement.Functions.Services;
global using NSubstitute;
global using NUnit.Framework;
