global using System.Text.Json;
global using MovieManagement.TMDB.Api.Mappers;
global using MovieManagement.TMDB.Api.Services;
global using MovieManagement.TMDB.Api.Config;
global using Microsoft.EntityFrameworkCore;
global using MovieManagement.Database.Config;
global using MovieManagement.Database.Repositories;
global using MovieManagement.Database.Context;
global using MovieManagement.Domain.Models.TMDB;
