global using Blazored.Modal;
global using MovieManagement.Domain.Models;
global using MovieManagement.ViewModels.MovieDetails;
global using MovieManagement.TMDB.Api.Mappers;
global using MovieManagement.TMDB.Api.Services;
global using MovieManagement.TMDB.Api.Config;
global using Microsoft.AspNetCore.Components;
global using Microsoft.JSInterop;
global using System.Text.Json;