# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Test Blazor Application

on:
  push:
    branches-ignore:
      - main
env:
  BLAZOR_PROJECT: ./src/MovieManagement/MovieManagement.csproj
  TEST_PROJECT: ./test/MovieManagement.Test/MovieManagement.Test.csproj
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore "${{ env.BLAZOR_PROJECT }}"
    - name: Build
      run: dotnet build "${{ env.BLAZOR_PROJECT }}" --configuration Release --no-restore
    - name: Test
      run: dotnet test "${{ env.TEST_PROJECT }}"
