# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Blazor Application

on:
  push:
    branches-ignore:
      - main
env:
  BLAZOR_PROJECT: ./src/MovieManagement/MovieManagement.csproj
  DOMAIN_CLASS_LIBRARY: ./src/MovieManagement.Domain/MovieManagement.Domain.csproj
  TEST_PROJECT: ./test/MovieManagement.Test/MovieManagement.Test.csproj
  FILE_NAME: test-results.xml
  FILE_TITLE: Tests
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Restore dependencies
      run: | 
          dotnet restore "${{ env.DOMAIN_CLASS_LIBRARY }}" 
          dotnet restore "${{ env.BLAZOR_PROJECT }}"
    - name: Build
      run: |
          dotnet build  "${{ env.DOMAIN_CLASS_LIBRARY }}" 
          dotnet build "${{ env.BLAZOR_PROJECT }}" --configuration Release
    - name: Test
      run: |
        dotnet test "${{ env.TEST_PROJECT }}" --list-tests
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: 'Test Run'
        path: ${{github.workspace}}/${{env.FILE_NAME}}     
