# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Blazor Application

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
    BLAZOR_PROJECT: ./src/MovieManagement/MovieManagement.csproj
    DOMAIN_CLASS_LIBRARY: ./src/MovieManagement.Domain/MovieManagement.Domain.csproj
    TEST_PROJECT: ./test/MovieManagement.Test/MovieManagement.Test.csproj
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
        
      - name: Dotnet restore
        run: | 
          dotnet restore "${{ env.DOMAIN_CLASS_LIBRARY }}" 
          dotnet restore "${{ env.BLAZOR_PROJECT }}"

      - name: Build with dotnet
        run: |
          dotnet build  "${{ env.DOMAIN_CLASS_LIBRARY }}" 
          dotnet build "${{ env.BLAZOR_PROJECT }}" --configuration Release
        
      - name: Test
        run:  dotnet test "${{ env.TEST_PROJECT }}" --no-build

      - name: dotnet publish
        run: |
          dotnet publish "${{ env.DOMAIN_CLASS_LIBRARY }}" -c Release -o ${{env.DOTNET_ROOT}}/myapp
          dotnet publish "${{ env.BLAZOR_PROJECT }}" -c Release -o ${{env.DOTNET_ROOT}}/myapp
          dotnet publish "${{ env.TEST_PROJECT }}" -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sep6group2moviemanagement'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5D8F6A89B4944141B9886DDD710750AB }}
          package: .
